apiVersion: v2
name: functions-app
description: An example Helm chart for some application

type: application
version: 0.1.0

dependencies:
  - name: functions-lib
    version: 0.1.0
    repository: file://../functions-lib
