{{- define "example.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
      - name: colors
        image: argoproj/rollouts-demo:{{ .Values.color }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
{{- end -}}

{{- /* First we render the template into a variable. */ -}}
{{- $mainDeployment := include "example.deployment" . -}}

{{- /*
  And then we pass that rendered template so our stable and preview objects are
  rendered. The original scope / context has to be passed to the partial
  template, so we're giving it a list as a scope.
*/ -}}

{{- include "bluegreen.deployments" (list . $mainDeployment) -}}
